class CampanyPageConstants:
    INPUT_DESCRIPTION_APP_MAX = "Тестовое описаниеи ограничениефффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффФФФФФФ"
    INPUT_DESCRIPTION_APP = "Тестовое описание"
    INPUT_TARGETING_MIN = "90"
    INPUT_TARGETING_MAX = "99 999 999 999 999"
    INPUT_TARGETING = "101"
    INPUT_TITLE_ADV_MAX = "Тест на ограничениеееееееееееееееееееееееееееееееееееееееееееееЕЕЕЕЕЕЕЕЕЕЕЕЕЕ"
    INPUT_TITLE_ADV = "ВК PRODIGY"
    INPUT_DESCRIPTION_ADV = "Перспективная команда из Москвы"
    INPUT_EDIT_CAMPANY_ADD_NEW_BUDGET = "121"
    INPUT_EDIT_CAMPANY_ADD_NEW_CITY = "Санкт-Петербург"
    INPUT_DESCRIPTION_ADV_EDIT = "Тестовое описание после редактирования"
    ERR = "ERROR"
    STATUS_OK = "OK"
