from selenium.webdriver.common.by import By


class CampanyPageLocators:
    OPEN_FILTR = (By.XPATH, "//span[@class='vkuiButton__in']//span[text()='Фильтр']")
    IS_OPEN_FILTR = (By.XPATH, '//botton[@class="vkuiButton vkuiButton--size-l vkuiButton--mode-outline vkuiButton--appearance-neutral vkuiButton--align-center vkuiTappable vkuiInternalTappable vkuiTappable--hasHover vkuiTappable--hasActive vkui-focus-visible"]')
    SAVED_FILTR = (By.XPATH,  '//span[text()="Сохранённые"]')
    IS_SAVED_FILTR = (By.XPATH, '//div//[@class"SavedFilters_wrapper__fsh6J"]')
    DELETE_FILTR = (By.XPATH, "//div[@class='SavedFilters_closeIconWrap__Q-5yn vkuiTappable vkuiInternalTappable vkuiTappable--hasHover vkuiTappable--hasActive vkui-focus-visible']")
    APPLY_FILTR = (By.XPATH, "//span[@class='vkuiTypography vkuiTypography--normalize vkuiTypography--weight-3 vkuiSimpleCell__children vkuiHeadline--sizeY-compact vkuiHeadline--level-1' and text()='2223']")
    FILTR_LAUNCHED = (By.XPATH, "//span[@class='vkuiTypography vkuiTypography--normalize vkuiCheckbox__titleBefore vkuiText vkuiText--sizeY-compact' and text()='Запущенные']")
    FILTR_DELETE_CURR_DIR_APPLY = (By.XPATH, "//span[@class='vkuiButton__content' and text()='Сбросить']")
    FILTR_DELETE_ALL_APPLY = (By.XPATH, "//span[@class='vkuiButton__content' and text()='Сбросить все']")
    FILTR_APPLY_ALL = (By.XPATH, "//span[@class='vkuiButton__content' and text()='Выбрать все']")
    FILTR_STATUS_CAMPANY_LAUNCHED = (By.XPATH, "//span[text()='Запущенные']")
    FILTR_STATUS_CAMPANY_STOPED = (By.XPATH, "//span[text()='Остановленные']")
    FILTR_STATUS_SHOW_DELETED = (By.XPATH, "//span[text()='Показать удалённые']")
    OPEN_FILTR_STATUS_MODER = (By.XPATH, "//div[@class='FiltersCategoryItem_filterGroup__0brn5']//span[text()='Статус модерации']")
    FILTR_STATUS_MODER_ON_CHECK = (By.XPATH, "//label[.//span[text()='На проверке']]")
    FILTR_STATUS_MODER_DENIED = (By.XPATH, "//label[.//span[text()='Отклонена']]")
    FILTR_OPEN_OBJ_ADV = (By.XPATH, "//div[@class='FiltersCategoryItem_filterGroup__0brn5']//span[text()='Объект рекламы']")
    FILTR_STATUS_OBJ_ADV_MOBILE = (By.XPATH, "//span[text()='Мобильное приложение']")
    FILTR_OPEN_TRANSLATION = (By.XPATH, "//div[@class='FiltersCategoryItem_filterGroup__0brn5']//span[text()='Трансляция']")
    FILTR_TRANSLATION_ON = (By.XPATH, "//span[@class='vkuiTypography vkuiTypography--normalize vkuiCheckbox__titleBefore vkuiText vkuiText--sizeY-compact' and text()='Транслируется']")
    FILTR_TRANSLATION_OFF = (By.XPATH, "//span[@class='vkuiTypography vkuiTypography--normalize vkuiCheckbox__titleBefore vkuiText vkuiText--sizeY-compact' and text()='Не транслируется']")
    FILTR_OPEN_EFFICIENCY = (By.XPATH, "//div[@class='FiltersCategoryItem_filterGroup__0brn5']//span[text()='Эффективность кампании']")
    FILTR_EFFICIENCY_GOOD = (By.XPATH, "//label[.//span[contains(text(), 'Эффективные')]]")
    FILTR_EFFICIENCY_MAKE_BETTER = (By.XPATH, "//label[.//span[contains(text(), 'Можно улучшить')]]")
    FILTR_CANCEL = (By.XPATH, "//span[@class='vkuiButton__in']//span[@class='vkuiButton__content' and text()='Отмена']")
    FILTR_APPROVE = (By.XPATH, "//span[@class='vkuiButton__in']//span[@class='vkuiButton__content' and text()='Применить']")
    FILTR_SAVE_OPEN = (By.XPATH, "//span[text()='Сохранить']")
    FILTR_SAVE_CLOSE = (By.XPATH, "//div[@tabindex='0' and @role='button' and @aria-label='Закрыть' and contains(@class, 'vkuiModalDismissButton')]")
    FILTR_SAVE_INPUT = (By.XPATH, "//input[@class='vkuiTypography vkuiInput__el vkuiText vkuiText--sizeY-none' and @type='text']")
    FILTR_SAVE_CONFIRM = (By.XPATH, "//span[@class='vkuiButton__in']//span[@class='vkuiButton__content' and text()='Сохранить']")
    FILTR_REMOVE = (By.XPATH, "//button[@type='button' and @aria-label='Удалить ' and contains(@class, 'vkuiChip__remove')]")
    OPEN_CREATION_NEW_CAMPANY = (By.XPATH, "//span[text()='Создать']")
    CHOOSE_SOCIETY = (By.XPATH, "//span[text()='Сообщество и профиль']")
    DROPDOWN_ADVS_OBJECT = (By.XPATH, "//input[@data-testid='vk-owner-selector']")
    CHANGE_NAME_CAMPANY = (By.XPATH, "//h2[text()='Кампания 2024-12-07']")
    INPUT_NEW_NAME = (By.CLASS_NAME, 'EditableTitle_inputContainer')
